[package]
name = "proc-macros"
version = "0.1.0"
authors = ["swerdloj <swerdloj@andrews.edu>"]
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
